name: PolyakovPy Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
    - main
    - feature/*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.0.0
      with:
        python-version: "3.10"
        architecture: 'x64'
      
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        python -m pip install pandas
        python -m pip install tqdm
        python -m pip install argparse
        python -m pip install requests
        
        
    - name: Download data from kpolyakov.spb.ru
      run: 
        python ./download_data.py
    
    - name: Test with unittest
      run: |
        python -m run_all_tests
        
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: failed_tests
        path: tmp
