name: PolyakovPy Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
    - main
    - feature/*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.0.0
      
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        python -m pip install pandas
        python -m pip install tqdm
        
    - name: Download data from kpolyakov.spb.ru
      run: 
        python ./download_data.py
    - name: Test with unittest
      run: |
        python -m unittest discover -p "problem*.py" -v
